### ISSUE TITLE
A number of redundant PVCs appear within the demo namespace

### ISSUE THREAD

**Issue by edseymour** [RedHatEMEA/demobuilder#111]
If you list the pvcs in the system, you'll see a quite a few in the demo namespace. These are causing errors in the openshift-master as they cannot be fulfilled. 

## find PVC
`oc get pvc --all-namespaces`

## remove PVC
`oc delete pvc --all -n demo`

**Comment by jim-minter** [comment]
I don't believe this is an issue in 3.1.  What would be good is capability to do a demo with PVCs - this is #37.
