### ISSUE TITLE
All people to label issues in demobuilder

### ISSUE THREAD

**Issue by edseymour** [RedHatEMEA/demobuilder#113]
It would be helpful if reporters could also label issues as they create/edit them - is this a permissions thing?

**Comment by jim-minter** [comment]
Yes, it is.  Ed, I've added you to the team so you can tag issues to your heart's content.  Anyone else who wants membership should contact me.

**Comment by edseymour** [comment]
Thanks, am now a member - but still not seeing an option to label - have I missed something!?

**Comment by jim-minter** [comment]
Mm, you're right :(
https://help.github.com/articles/issues-only-access-permissions/
