### ISSUE TITLE
bzip2 needs to be installed to allow install of VBoxGuestAdditions on 3.1 demo server

### ISSUE THREAD

**Issue by ffirg** [RedHatEMEA/demobuilder#114]
Please add the bzip2 package to the demo server builds so the VirtualBox GuestAdditions can be installed. It fails otherwise. I used the new 3.1 image on Amazon.

**Comment by ffirg** [comment]
Also same issue with the 3.0 Amazon image

**Comment by jim-minter** [comment]
Sorry @ffirg , I'm not keeping up with you.  You want the /VirtualBox/ guest additions when running on /Amazon/?

**Comment by ffirg** [comment]
No. Your pre baked image needs to include the bzip2 package, that's all.
Sorry should have made it clearer!
Without bzip2 you can't install/upgrade the Guest Additions. It fails when
trying to extract the files.

**Comment by jim-minter** [comment]
But when the vagrant-virtualbox target layer is added, it adds the VirtualBox guest additions for you.  It does this by installing bzip2, unpacking and installing the guest additions.  Currently it then removes bzip2 at the end.

- is the vagrant-virtualbox target sufficient for your needs? If not, why not? :)
- is there a specific reason why you think bzip2 should be kept after installing the guest additions?

**Comment by ffirg** [comment]
Ah I see. Wondered how you had it installed in the first place.
I would keep bzip2 in there, else you can't upgrade the guest tools, which
might be useful.

**Comment by jim-minter** [comment]
Hmm, I guess the point of these images is that they're short-lived, you just download a new one and we upgrade the guest tools at source.  In any case, it's not just bzip2 in question, it's kernel-devel and gcc, which take a fair amount of additional space.

**Comment by ffirg** [comment]
Ok, it's only a small issue so no biggie. I only needed to install bzip2 to
get it to work. It pulled in -libs but that's all.

**Comment by jim-minter** [comment]
Spring cleaning - I don't believe there's any action due here - if you think otherwise, please feel free to re-open.
