### ISSUE TITLE
Build in cluster metrics in the all-in-one offline demo build

### ISSUE THREAD

**Issue by ffirg** [RedHatEMEA/demobuilder#115]
Setup as per https://docs.openshift.com/enterprise/3.1/install_config/cluster_metrics.html
So Heapster/Hawkular etc setup inside the openshift-infra project

**Comment by jim-minter** [comment]
This should be working in the ose3.1 (base) layer with 0790130b79149f43aee5b61f5eb2e2f03d50fd56 - just rebuilding images for internal use now...

**Comment by jim-minter** [comment]
3.1 images with this are now live :)

**Comment by ffirg** [comment]
Nice one. Thanks Jim :)
