### ISSUE TITLE
May want to add httpd-tools package to distro so you can use ab to do CPU load testing

### ISSUE THREAD

**Issue by ffirg** [RedHatEMEA/demobuilder#124]
yum -y install httpd-tools (adds httpd-tools, apr and apr-utils).
This allows you to run ab which can be used to stress test your app and showcase horiztonal cpu scaling as per : https://blog.openshift.com/openshift-3-1-pod-autoscaling/?utm_source=OpenShift+Online&utm_campaign=534c76c35a-Newsletter_2015-12&utm_medium=email&utm_term=0_c528e5e48e-534c76c35a-108181341

**Comment by jim-minter** [comment]
This was done in 7ee6abdecc2554a63e4926622cd8b71ec49179f7 and should be available already.
