### ISSUE TITLE
OSE31 Offline Demo image poor performance

### ISSUE THREAD

**Issue by utherp0** [RedHatEMEA/demobuilder#130]
More of a question than an issue, I'm running the OSE31 offline demo image via Vagrant and VirtualBox and have only two projects, one running a single instance of the EAP64 with kitchensink and the other running a Docker build based App using the latest JWS and a simple introspection application via WAR rather than S2I.

After two minutes of operation the VM consistently runs extremely poorly, unresponsive to windows events, fan active on MacBook Pro. Running top shows non excessive operation within the VM, with Openshift taking around 25-30% of CPU.

No other applications running on the MacBook Pro (16GB) - I'm only seeing this slowdown since I updated to El Capitan to address a MacMail issue, is anyone seeing severe degraded performance with this kind of setup?

**Comment by ffirg** [comment]
I have had similar experiences under the same setup.  Only intermittent
performance issues though. Very very rate I have to reboot the VM.

**Comment by utherp0** [comment]
As a follow-up, I've done clean rebuilds, running singular apps and I'm still seeing the same consistent performance issues - it runs for five or so miinutes and then the performance degrades to the point that the VM becomes completely unresponsive.

**Comment by ffirg** [comment]
Might be worth trying vmware player or fusion in place of virtualbox?

**Comment by utherp0** [comment]
What I've done is got a clean F22 build, in the process of updating, and
I'll try the other image and see if I get/don't get the same issues.

On Thu, Jan 21, 2016 at 12:05 PM, Phil Griffiths <notifications@github.com>
wrote:

> Might be worth trying vmware player or fusion in place of virtualbox?
>
> On 21 January 2016 at 11:11, utherp0 <notifications@github.com> wrote:
>
> > As a follow-up, I've done clean rebuilds, running singular apps and I'm
> > still seeing the same consistent performance issues - it runs for five or
> > so miinutes and then the performance degrades to the point that the VM
> > becomes completely unresponsive.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/RedHatEMEA/demobuilder/issues/130#issuecomment-173540127
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedHatEMEA/demobuilder/issues/130#issuecomment-173551441>
> .
>



-- 
Ian 'Uther' Lawson
Senior Solution Architect
JBoss/Openshift/Infrastructure, Red Hat UK PubSec

E-Mail: ilawson@redhat.com
Mobile: 07803349094

Red Hat UK, 200 Fowler Avenue, Farnborough, Hampshire, GU14 7JP
https://uk.linkedin.com/in/ian-lawson-a0199011

**Comment by jim-minter** [comment]
I'm not sure there's anything immediately to be done about this, so closing the issue.
* please try the latest published image if you're not on it.
* please ensure you're giving the VM 8GB of RAM (default on latest image)
* also I believe that significant cpu usage improvements to k8s are due to be shipped in ose 3.2
