### ISSUE TITLE
"/etc/pki/ca-trust/sources/anchors/" in install instructions is "source" on F22. 

### ISSUE THREAD

**Issue by jamesread** [RedHatEMEA/demobuilder#26]
Mostly raising this issue to see if I can raise a clean PR against it.

**Comment by jamesread** [comment]
Okies, I've got the changes into a feature branch in my fork, that's looking a little better I think; https://github.com/jamesread/demobuilder/tree/issue26

**Comment by jim-minter** [comment]
Commit added manually, thanks, please issue a clean PR (containing a single commit) next time :)

**Comment by jamesread** [comment]
Heh, I was experimenting mostly then got distracted with a meeting. I'll try again on my own repo.
