### ISSUE TITLE
multiple environments (promotion of docker images)

### ISSUE THREAD

**Issue by jim-minter** [RedHatEMEA/demobuilder#38]

**Comment by jim-minter** [comment]
@edseymour this could be done by tagging imagestreams?

**Comment by edseymour** [comment]
I think so - it's basic but the idea was to create a 2nd project, e.g. 'prod' to show an app being promoted from 'demo' to 'prod'. 

* In dev we should a s2i lifecycle, with the dev deployment config watching the :latest tag and deploying with each new build
* In prod we have a pre-configured deployment config that deploys 3 replicas and rolling strategy, and is trigger by a change to the imagestream, but is watching a different tag, e.g. :stable
* To demonstrate promotion we tag :latest with :stable and that should automatically start a new deployment in the prod project. 
* Watching the web console, the user should see a new deployment being created alongside the original deployment, with pods for the new deployment appearing and pods of the old deployment disappearing until deployment has completed. 
* A nice to have would be some visualisation of the the switch to v2 in a web browser - to work best, it will need to poll the page. Perhaps some text that changes from "Version 1" to "Version 2" (or something a little less prosaic!)
