### ISSUE TITLE
tomcat7 and tomcat8 template-based projects fail due to fault in template

### ISSUE THREAD

**Issue by edseymour** [RedHatEMEA/demobuilder#41]
The tomcat7/8 templates 

\-    name: {APPLICATION_NAME}-tcp-8080
\+   name: tcp8080

(as system:admin)
\# oc edit templates/jws-tomcat7-basic-sti -n openshift

issue replicated in jws-tomcat8-basic-sti and possiblu others.

**Comment by jim-minter** [comment]
should be fixed in 745e90b8a895f69b08e40b5dc0f47eb32a043043 ; await rebuild
