### ISSUE TITLE
Outline how a user can become an OSE admin user in CLI 

### ISSUE THREAD

**Issue by ivanthelad** [RedHatEMEA/demobuilder#47]
for example 
    - ssh root@openshift.example.com

**Comment by jim-minter** [comment]
sudo [-i|-s], FWIW - but yes, this needs to be documented somewhere

**Comment by ivanthelad** [comment]
or have a preconfigure user that has cluster admin rights

**Comment by jim-minter** [comment]
fixed in 2bd528c93afe5a8fe1269c35988ed28939e7c42f
