### ISSUE TITLE
4gb memory not enough for ticketmonster demo

### ISSUE THREAD

**Issue by jim-minter** [RedHatEMEA/demobuilder#51]

**Comment by alberttwong** [comment]
I'm having the same problem.  works better when using 8gb.

**Comment by jim-minter** [comment]
Agreed.  I'd rather fix the memory usage than increase the VM size if possible.  First plan of attack is trying to reduce the Java heap sizes and see if that helps.  Anyone care to take a crack at it?

**Comment by jim-minter** [comment]
e39bcf0ee427687f75485dbf0c9fb5987e6b92a2 will pick this up

**Comment by alberttwong** [comment]
Just FYI... I fixed this by modifying the Vagrantfile.    I've put in a pull request to update the documentation on how to do this.

**Comment by jim-minter** [comment]
I'm on the verge of capitulating and increasing the memory to 8GB, particularly now we've got the logging and metrics pieces.  See #118.
