### ISSUE TITLE
RAM is reserved for the kdump kernel

### ISSUE THREAD

**Issue by christianhorn** [RedHatEMEA/demobuilder#58]
The openshift 3.0.1 offline image (and possibly others) have "crashkernel=auto" configured, which leads to RAM beeing reserved for kdump instead of beeing available for the kernel:

$ dmesg|grep crash
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-3.10.0-229.11.1.el7.x86_64 root=UUID=3e97515d-5a4a-418c-9754-252537d3ff45 ro crashkernel=auto LANG=en_US.UTF-8 net.ifnames=0
[    0.000000] Reserving 161MB of memory at 704MB for crashkernel (System RAM: 4095MB)

This is probably not desired for this usage, the crashkernel option should be removed.

**Comment by jim-minter** [comment]
Good catch - should be fixed in 3bc0db31f69de7310ed6b4afd896a02c4dc014e2 - thanks!
