### ISSUE TITLE
Integrate the latest JBDS and OSE3 plugin 

### ISSUE THREAD

**Issue by ivanthelad** [RedHatEMEA/demobuilder#64]
Often it is required to show the latest eclipse openshift functionality. 
It would be worthwhile to perhaps replace JBDS 8 with jbds 9 which comes with ose3 support ottb.

**Comment by jim-minter** [comment]
+1 - I had been waiting for JBDS 9 to GA, but if what it offers is valuable and stable enough we could bring it forward.  Can you start by trying it out and reporting back whether in your opinion we should bring it in now or wait?

**Comment by ivanthelad** [comment]
I've tried it out from a ose perspective. its not full featured but theres some cool things  it can do.
 - point eclipse to OSE3 application. Generate a eclipse project based on a S2I based application. (this could be cool for you demo .. do a new-app https://github.com.. then go to eclipse and import project)
 - Create Applications on ose3 based on templates in OSE3(eap, tomcat, php. but also pure code)
 - browse projects and resources in projects and view attributes 

i did not test things like SCM but would assume this works

**Comment by jim-minter** [comment]
As of a7734ee9970815dacf51a9ed6b94bbb5d086ff6c , this is in demobuilder - but images not built yet.

**Comment by jim-minter** [comment]
done!
