### ISSUE TITLE
Support for RHEL6 environments

### ISSUE THREAD

**Issue by edseymour** [RedHatEMEA/demobuilder#65]
The RHEL7 image may not work on RHEL6 reporting a version issue with the underlying qcow2 image. 

It was possible to hack the the box image by converting the box.img found in $HOME/.vagrant.d/boxes/rhel-server-7\:gui\:ose-3.0\:offline\:demo-jminter\:vagrant-libvirt/0/libvirt/

The convert command was
> qemu-img convert -f qcow2 -O qcow2 -o compat=0.10 box.img new-box.img

Where new-box.img was then used to replace the original box.img.
A new vagrant init was required, then it was possible to "vagrant up"

It was noted that the new-box.img was approximately doubled in size at about 9GB

**Comment by jim-minter** [comment]
Ah, interesting, I was wondering if we'd hit this at some point.  Probably just patching the 8th byte of the qcow file from 0x03 to 0x02 would also have done it.  Recent Fedora and RHEL7 have revved the internal qcow2 version and added further features but as things stand we're not doing anything with them, so we're not building anything wildly incompatible.

The reason the qcow2 file blew up when you converted it was that you omitted '-c' to compress the destination file.

We should indeed build v2 qcow2 images by default.

**Comment by jim-minter** [comment]
should be fixed in a5c396427c2b6c479c3cb8604473a7ce1e01e589

**Comment by edseymour** [comment]
BTW, had a problem with the "-c" option, when used received an error (e.g. qemu-img: error while compressing sector 60276864: Input/output error)

**Comment by jim-minter** [comment]
Almost certainly https://bugzilla.redhat.com/show_bug.cgi?id=1214855 - ensure you're on >= qemu-2.3.0-6.fc22

**Comment by edseymour** [comment]
Yep, bang on, 2.3.0 currently installed, need to update.
