### ISSUE TITLE
Remote desktop too slow for demos

### ISSUE THREAD

**Issue by jbrannst** [RedHatEMEA/demobuilder#72]
Using VirtualBox built-in desktop viewer, the display is very laggy and greatly slows down learning and complicates a demo. For bluejeans demos, this is not an issue, the connection is typically laggy anyway.

Add a minimum spec required so we can order new HW?
Recommend a better viewer?
Allow host browser access to OSE console?

**Comment by jbrannst** [comment]
HW specs are relevant for a performance issue, mine: 
https://support.apple.com/kb/SP703?locale=en_US

**Comment by alberttwong** [comment]
I upped the amount of ram in the vagrantfile and it seemed ALOT better.   Upped it to 8GB.   Updated the documentation to reflect that.

**Comment by jim-minter** [comment]
I think the only appropriate fix is in #118 and maybe #69; closing this issue.
