### ISSUE TITLE
Installation routines for layers should run independently of vm creation 

### ISSUE THREAD

**Issue by sbadakhc** [RedHatEMEA/demobuilder#77]
I think its necessary to split your installation layer from virtual machine creation.  The install scripts should assume a provisioned vm and simply test for the correct OS and perhaps minimum system requirements before executing.  I ran into similar problems with my Kojak project and found it was much easier to split the demo into create vm stage, install and then configure.  This allowed us a lot of flexibilty and got people over many or the hurdles associated with the end users choice of hypervisor.

**Comment by jim-minter** [comment]
Sorry, I think either demobuilder is already following this advice, or, where not that the advice doesn't fit with the demobuilder project goals.  Closing this issue but happy to have a verbal discussion about it if useful.
