### ISSUE TITLE
Mac OSX - Vagrant up issue

### ISSUE THREAD

**Issue by gkrishnan2015** [RedHatEMEA/demobuilder#78]
Followed the installation instructions (to the tee - with an end user perspective) for the OpenShift 3.0.1 offline image with Jim's demo. I get the following error on the vagrant up command (new SA & new to Mac!!). Not sure if anybody else has seen this...
<img width="568" alt="screen shot 2015-09-23 at 12 05 08 pm" src="https://cloud.githubusercontent.com/assets/14810248/10055718/a6e41016-61ec-11e5-91bc-6730d1544060.png">

**Comment by jim-minter** [comment]
Hi @gkrishnan2015 , please subscribe to demobuilder-list and e-mail there for help - GitHub issues are to track issues needing code changes.  I've sent you an e-mail reply cc the list, hopefully I sent it to the right person!
