### ISSUE TITLE
Demonstrate rolling deployment feature

### ISSUE THREAD

**Issue by ivanthelad** [RedHatEMEA/demobuilder#96]
with respect to the monster demo. where end user creates a app then edits code and redeploy image. 
During the redeployment the application is unavailable as the existing app disappears while the new one is not yet ready and is just coming up. 

Recommendation. 
 -Scale the app first to 2 instances 
- Make code changes

Benefit 
 - Application is always available 
 - demo rolling deployment occurs. two instances always available.

**Comment by jim-minter** [comment]
actually I've pretty much just implemented this following on from Ed's work - new images arriving soon!

**Comment by ivanthelad** [comment]
this will impact the "debugging" aspect of the demo as you will have no idea which node your request will land on.

**Comment by alberttwong** [comment]
Phil wrote in the maililng list about his script.  I've added it to the docs.   What we're missing now is just the demo steps.

**Comment by jim-minter** [comment]
I think rolling deployment is covered off fairly adequately with the monster-prod workflow.  I'm hooing #117 will cover @alberttwong's comment
