### ISSUE TITLE
Debugger configured for 127.0.0.1 instead of localhost

### ISSUE THREAD

**Issue by ivanthelad** [RedHatEMEA/demobuilder#97]
The instructions outline only the port should be changed for debugging. You should also change the host config. using localhost does not allow JBDS to connect to the debugger. 

Start debugging.
Return to JBoss Developer Studio.
Click Run/Debug Configurations....
Double-click Remote Java Application in the list on the left.
Change localhost to 127.0.0.1 
Change the port number on the right from 8000 to 8787 and click Debug.

**Comment by jim-minter** [comment]
localhost works for me - can you do some digging and find out why it doesn't for you?

**Comment by jim-minter** [comment]
Haven't encountered this or heard of the issue from anyone else - closing.
