### ISSUE TITLE
seems to take longer than ose3 rolling upgrade time for monster front page to change

### ISSUE THREAD

**Issue by jim-minter** [RedHatEMEA/demobuilder#99]
cookies in the router tier?

**Comment by alberttwong** [comment]
I don't think it is that.  I had the same problem.  I wrote in the docs that you just have to wait for the imagestream to kick off.  I had to wait about a minute.

**Comment by jim-minter** [comment]
Indeed, it wasn't cookies in the routing tier.  I eventually got to this at https://github.com/jim-minter/ose3-demos/commit/65d2ab4b82e6ad2b763e138f5fd9e1e20ae9e443 . I believe this is fixed in the ose-3.1 images.
